### ISSUE TITLE
add support $evmProxy->trigger($eventName)

### ISSUE THREAD

**Issue by samsonasik** [pennyphp/penny#118]
currently, we must pass `PennyEventInterface` in trigger() method, this is will make limitation for eventManager out there, as new interface need to be created to implements the Proxy for custom EventManager, how about add string support passed parameter to string as event Name/ key ? it will make easier to adapt? So, it will be:

``` php
    /**
     * Triggerer event
     *
     * @param PennyEventInterface|string $event Trigger specific event
     */
    public function trigger($event);
```

**Comment by gianarb** [comment]
I understand your feedback and sounds good :) 

PennyEventInterface helps me to create a standard event.. Without this Interface we cannot safe that our event will support a `getResponse` for example.

What do you think? :) @wdalmut @fntlnz can you share your feedback please? :+1:

**Comment by samsonasik** [comment]
I'm closing it, feel free to open if needs more discussion, seems it not possible due the eventmanager usage, probably need many refactor  if we want to support it. Btw, I opened #120 for cakephp eventmanager proxy ;)

**Comment by samsonasik** [comment]
re-open in favor of #121
