### ISSUE TITLE
remove "Penny-" prefix from Event interfaces

### ISSUE THREAD

**Issue by samsonasik** [pennyphp/penny#139]
As there is no other interfaces/classes that have Penny prefix, I think Penny- prefix can be removed from Event Interfaces, so:
- `Penny\Event\PennyEvmInterface` can be changed to `Penny\Event\EventManagerInterface`
- `Penny\Event\PennyEventInterface` can be changed to `Penny\Event\EventInterface`

@gianarb what do you think ? /cc @fntlnz @EmanueleMinotto

**Comment by gianarb** [comment]
Sounds good :)

**Comment by samsonasik** [comment]
I've created PR https://github.com/pennyphp/penny/pull/140 for it ;)

**Comment by EmanueleMinotto** [comment]
:+1:
