### ISSUE TITLE
silently RuntimeException when !$routeInfo instanceof RouteInfoInterface

### ISSUE THREAD

**Issue by samsonasik** [pennyphp/penny#148]
because it inside of try ... catch: 
- https://github.com/pennyphp/penny/blob/master/src/App.php#L145-L147
- https://github.com/pennyphp/penny/blob/master/src/App.php#L123-L129

see https://3v4l.org/sYFO2

**Comment by samsonasik** [comment]
I created PR https://github.com/pennyphp/penny/pull/149 for it ;)

**Comment by gianarb** [comment]
I don't understand.. It is an error handler.. it is not silent..

**Comment by samsonasik** [comment]
did you check https://3v4l.org/sYFO2  ?

**Comment by samsonasik** [comment]
also, it never catched, as I updated the PR at #149 https://github.com/pennyphp/penny/pull/149/files?diff=split `testDispatcherNotInstanceOfPennyDispatcher` as previously silently on tests.

**Comment by samsonasik** [comment]
I was wrong on 3v4l usage, but it actually not thrown on this try-catch case, and I prefer the validation should on Dispatcher as Dispatcher will return RouteInfo class, otherwise will throw exception class in Dispatcher __invoke.
