### ISSUE TITLE
enable code coverage

### ISSUE THREAD

**Issue by samsonasik** [pennyphp/penny#18]
currently, code coverage is not shown in codecoverage button

**Comment by gianarb** [comment]
Fixed thanks!

![https://camo.githubusercontent.com/d0a2562170725cf0310abfd464bb019718a6eef0/68747470733a2f2f7363727574696e697a65722d63692e636f6d2f672f6769616e6172622f70656e6e792f6261646765732f636f7665726167652e706e673f623d6d6173746572](https://camo.githubusercontent.com/d0a2562170725cf0310abfd464bb019718a6eef0/68747470733a2f2f7363727574696e697a65722d63692e636f6d2f672f6769616e6172622f70656e6e792f6261646765732f636f7665726167652e706e673f623d6d6173746572)
