### ISSUE TITLE
Discussion channels

### ISSUE THREAD

**Issue by fntlnz** [pennyphp/penny#34]
We should consider setting up a discussion channel for penny.

Options that come to mind are:
- irc
- Google groups
- Traditional mailing list
- Gitter
- Slack

My favourite option is a combination between irc and google groups.

The main reason why I prefer irc instead of gitter or slack is because I'm pretty sure that it will be there for the next decade and as a plus it's likely that it won't change in that time frame.

On the other hand I would like to have something like a mailing list or a Google Group to engage long term durable conversations for which a chat would not fit.

What do you think?

**Comment by fntlnz** [comment]
Maybe @samsonasik and @EmanueleMinotto have something to say about this

**Comment by EmanueleMinotto** [comment]
Google groups + IRC sounds good for me too :+1:

**Comment by ovr** [comment]
Gitter/Slack :+1:

**Comment by EmanueleMinotto** [comment]
@ovr you forgot to add -> :trollface:

**Comment by gianarb** [comment]
At the moment IRC + Github Issue.. 
Google groups is a good tool but now we have a very little community.. 
I seems google groups in future

**Comment by samsonasik** [comment]
I am for Google Group and Github issue

**Comment by ovr** [comment]
@EmanueleMinotto I thought that we were playing a game "find troll", you win ;)

**Comment by gianarb** [comment]
I close this issue at the moment we work on github issue for all..

On IRC I'm gianarb and I joined to **#pennyphp** channel
