### ISSUE TITLE
pennyphp.org can't be access via https

### ISSUE THREAD

**Issue by samsonasik** [pennyphp/penny#38]
in the repository title, it uses https:  https://pennyphp.org:

```
 :moneybag: Php Framework made of other components
https://pennyphp.org
```

I can't access it via https, @gianarb is it works with https on yours?

**Comment by gianarb** [comment]
Mismatch.. :) the site ad the moment doesn't support https.. :)

Thanks!

**Comment by fntlnz** [comment]
That's terrible in 2015!
