### ISSUE TITLE
change httpflow with event manager

### ISSUE THREAD

**Issue by gianarb** [pennyphp/penny#52]
Only Http? I'm not sure that this is the best name for this concept..

I call it with a classic name EventManager

**Comment by samsonasik** [comment]
how about "app.flow" for naming?

Warm regards,

Abdul Malik Ikhsan

Pada 10 Sep 2015, pukul 18.55, Gianluca Arbezzano notifications@github.com menulis:

**Comment by gianarb** [comment]
Yeh.. :) it sounds good

**Comment by gianarb** [comment]
@samsonasik at the moment I prefer eventmanager it represents itself :D

**Comment by fntlnz** [comment]
I preferred the one suggested by @samsonasik .

`app.flow` was more significant about the fact that is handling a flow of events around in the application and was even better than `http.flow` because it made it decoupled from the concept of http in itself.

**Comment by gianarb** [comment]
to be honest you can use it to trigger all events into the application :)
We can use php-di alias to use it, if this stuff helps to understand :)
