### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by fntlnz** [pennyphp/penny#60]
We should create a `CONTRIBUTING.md` file to explain people a few conventions like these:
- Non-project related ignores must be in the global .gitignore or in the local git folder
- Coding style related things / operated by @EmanueleMinotto 
- Other (?)

What do you think?

**Comment by gianarb** [comment]
- Run tests
- Every PR contains only one feature and it is in its branch not into the master branch

**Comment by EmanueleMinotto** [comment]
- coding standard for the project is PSR-2
- any contribution must provide tests for additional introduced conditions
- pull requests must be sent from a new `hotfix/feature` branch, not from `master`

imo PHPDoc should be required too

Last proposal: @gianarb create your style using http://edorian.github.io/php-coding-standard-generator/ and add it to the main repo

**Comment by gianarb** [comment]
Thanks at all 
6a19e38faf66e8da57e54247e1882458b5993736
