### ISSUE TITLE
php-cs-fixer related issue

### ISSUE THREAD

**Issue by EmanueleMinotto** [pennyphp/penny#64]
php-cs-fixer automatically changes the namespace `namespace TestApp\Controller;` to `namespace Testapp\Controller;` in _tests/app/Controller/Index.php_

Don't know if it's a problem of php-cs-fixer or if penny is using a hack :\

**Comment by samsonasik** [comment]
not sure about that, I uses styleci in and seems in SanSessionToolbar the php-cs-fixer change that : https://github.com/samsonasik/SanSessionToolbar/blob/master/test/ModuleTest.php#L20 I am wondering why it makes lower case in end of it

**Comment by fntlnz** [comment]
What a weird thing :/

**Comment by gianarb** [comment]
penny doesn't use any hack.. mm can you try this operation with Linux (into the VM for example)

**Comment by EmanueleMinotto** [comment]
Sorry for the delay... yes, this issue seems to be defined also on a Linux VM (tested with [ideatosrl/vagrant-php-template](https://github.com/ideatosrl/vagrant-php-template)).

**Comment by samsonasik** [comment]
psr4 with php-cs-fixer is indeed problematic with case sensitive "Apptest" can't have namespace "AppTest", maybe open issue in php-cs-fixer repo?
