### ISSUE TITLE
scrutinizer badge keep show 94% coverage

### ISSUE THREAD

**Issue by samsonasik** [pennyphp/penny#72]
I think there is something in scrutinizer config that make it still only 94% instead of 100%. @gianarb  is vendor/ directory need to be excluded or backlisted in scrutinizer config ?

**Comment by gianarb** [comment]
WIP
c4c465dd9f0876393b74fa8a2849109f13608eb5

**Comment by gianarb** [comment]
Resolved

**Comment by samsonasik** [comment]
thanks.
