### ISSUE TITLE
Getting started foldering fonts not rendered correctly

### ISSUE THREAD

**Issue by fntlnz** [pennyphp/penny#89]
The fonts of the getting started foldering section are not rendered correctly on the website:
http://penny.readthedocs.org/en/feature-docs/getting-started/
While are rendered correctly by the github markdown parser:
https://github.com/pennyphp/penny/blob/master/docs/getting-started.md#foldering

![screen shot 2015-10-10 at 11 50 09](https://cloud.githubusercontent.com/assets/3083633/10410553/67cb83bc-6f45-11e5-91a6-061a81ed6edc.png)

I tried with many browsers on different operating systems and the problem persists

**Comment by gianarb** [comment]
Thanks but at the moment we don't support this branch..
https://github.com/rtfd/readthedocs.org/issues/1618

Your link is too old but I don't know how remove it from readthedocs

**Comment by fntlnz** [comment]
I found it searching on Google something like "pennyphp doctrine"

**Comment by gianarb** [comment]
eheh no good. I added new site into the google webmaster tool.. :) we can only wait.. Thanks
