### ISSUE TITLE
Increase event name readability/writability

### ISSUE THREAD

**Issue by gianarb** [pennyphp/penny#96]
I know that this proposal broke compatibility but I think to change

My proposal is:
To change `classname.method` (indexcontroller.index) with `class.method`.. In this way we can replace 

``` php
$eventManager->attach("indexcontroller.index", ...)
```

with

``` php
$eventManager->attach(IndexController::class.".index", ...)
```

Maybe this approach is more readable/writable.. What do you think?

**Comment by EmanueleMinotto** [comment]
I think a `::` should be used as separator for systems like that, this separator is also used "natively" by PHP to invoke static method: http://php.net/manual/en/language.types.callable.php (Example 1, Type 4)

**Comment by gianarb** [comment]
I use this syntax to print the namespace.. `IndexController::class`
`IndexController::class.".index" == "App\Controller\IndexController.index"}`

**Comment by EmanueleMinotto** [comment]
@gianarb reuse it? :D

**Comment by gianarb** [comment]
Guys.. Feedback to change this code?! 
@pennyphp/community-review @wdalmut @EmanueleMinotto 

IMO indexcontroller.index is very very very very ugly..

`App\Controller\IndexController.index`
`App\Controller\IndexController.index_error`
 maybe it sounds better

**Comment by samsonasik** [comment]
+1 for ::class usage

**Comment by samsonasik** [comment]
also, classname.method make collision when there is same classname but different namespace
